apiVersion: v1
kind: Service
metadata:
  name: user-management-nodeport-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30004
