apiVersion: v1
kind: Service
metadata:
  name: order-management-nodeport-service
spec:
  type: NodePort
  selector:
    app: order-management
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30003
