apiVersion: v1
kind: Service
metadata:
  name: payment-service-nodeport-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30002
