apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-deployment
  labels:
    app: product-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
        - name: product-management
          image: bugraugurtoygar/product-management:latest
          ports:
            - containerPort: 5173
