apiVersion: v1
kind: Service
metadata:
  name: product-management-nodeport-service
spec:
  type: NodePort
  selector:
    app: product-management
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30001
